name: nepika
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  image: ^4.5.4
  # UI & Icons
  # cupertino_icons: ^1.0.8
  # flutter_svg: ^2.0.9
  # lottie: ^2.7.0
  shimmer: ^3.0.0

  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  provider: ^6.1.0

  # Dependency Injection
  # get_it: ^7.6.4
  injectable: ^2.3.2

  # Networking
  dio: ^5.3.2
  http: ^1.1.0  # For SSE implementation

  # Local Storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.2.4

  # Camera & Media
  camera: ^0.10.5+5
  google_mlkit_face_detection: ^0.12.0

  image_picker: ^1.0.4
  permission_handler: ^11.3.1

  # Utilities
  # dartz: ^0.10.1
  connectivity_plus: ^5.0.1
  # intl: ^0.19.0
  json_annotation: ^4.8.0
  url_launcher: ^6.2.2
  share_plus: ^9.0.0
  
  # SMS Auto-read
  sms_autofill: ^2.4.0
  
  # Package Info
  package_info_plus: ^8.0.2
  
  # File type detection
  mime: ^1.0.6
  uuid: ^4.5.1
  flutter_local_notifications: ^19.4.2
  timezone: ^0.10.1
  firebase_core: ^3.3.0
  firebase_messaging: ^15.0.4
  firebase_core_platform_interface: ^5.4.2
  firebase_core_web: ^2.17.5
  
  # Stripe Payment Integration
  flutter_stripe: ^10.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_launcher_icons: ^0.13.1

  # Linting
  flutter_lints: ^5.0.0

  # Dependency Injection Codegen
  build_runner: ^2.4.7
  injectable_generator: ^2.4.1

  # Testing Utilities
  mockito: ^5.4.2
  bloc_test: ^9.1.5


flutter:
  uses-material-design: true

  assets:
    - assets/app/
    - assets/images/
    - assets/icons/
    - assets/icons/filled/

  fonts:
    - family: HelveticaNowDisplay
      fonts:
        - asset: assets/fonts/HelveticaNowDisplay-Regular.ttf
          weight: 400
        - asset: assets/fonts/HelveticaNowDisplay-Medium.ttf
          weight: 500
        - asset: assets/fonts/HelveticaNowDisplay-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/HelveticaNowDisplay-Bold.ttf
          weight: 700
        - asset: assets/fonts/HelveticaNowDisplay-Black.ttf
          weight: 900
